sudo: required

language: python

services:
  - docker

before_install:
  - docker pull consul
  - docker pull nginx
  - docker pull gliderlabs/registrator

script:
  - make build-stack

after_success:
  - make cleanup
